### ISSUE TITLE
Editor doesn't respect keywords separator

### ISSUE THREAD

**Issue by ifohancroft** [glutanimate/PDFMtEd#13]
When a document (in my use/test case, a PDF document) that has already been tagged and has more than one keyword added to it, gets opened in the editor, the editor separates the keywords with ';' regardless of what character is used/saved as the separator for the keywords.

This creates a problem, because when you open an already tagged document to change something, if you have a preference/need for a certain type of keyword separator, you have to change the keyword field, otherwise on save, regardless of what change has been made, the editor will override the keyword field and now the keywords will be separated by ';'.

What should happen instead, is the editor should show the keywords in the keywords field, separated by the separator character already used.

**Comment by glutanimate** [comment]
Hmm, this sounds reasonable to me. But can exiftool detect the separator automatically? (even if none has been explicitly been set in the past). It's been a while since I messed around with exiftool itself.

**Comment by ifohancroft** [comment]
According to my tests it seems it isn't a problem.
What I remember from reading the code when I was trying to find the culprit, you don't split the keywords anywhere, and the exiftool command works perfectly without specifying a separator so it's all good.

**Comment by ifohancroft** [comment]
Bump :D
