### ISSUE TITLE
Feature Request: Use of python3 only.

### ISSUE THREAD

**Issue by connaisseur** [glutanimate/PDFMtEd#21]
In README.md dependency list claims only the use of python3. "pdfmted-thumbnailer" completely relies on it --> Fine. 

**But** "pdfmted-editor" is still depending heavily on python2.7!

This makes it hard for distributions / packagers to clean systems from python2.7 if desired.

Could you please see for a fix on this?

**Comment by sonibla** [comment]
I think this is because of `Dependencies=(yad exiftool python2.7 qpdf)` in install.sh
I'll do a pull request to change it
The source code is already using python3

**Comment by Placidius** [comment]
I took the dependency out of the install.sh and it still says it requires python 2.7. There must be somewhere else in the code that requires it. I'm dumb though, and not qualified to fix such things.

**Comment by glutanimate** [comment]
Should be fixed now in `master` (thanks to @sonibla  and @mfraser!)
