### ISSUE TITLE
timestamps with .000000 in them are unhelpful

### ISSUE THREAD

**Issue by bremner** [Glutanimate/PDFMtEd#6]
When I rename according to tags, there is always .000000. after the year. I'm not sure if this is intentional, but I don't think it adds much.

**Comment by Glutanimate** [comment]
Thanks. This was a locale issue. It should be fixed with 6f269b34eabba12eae09de4df9a223eef9cafc06.

**Comment by Glutanimate** [comment]
Just noticed that I forgot to close this.
