### ISSUE TITLE
Python3 support?

### ISSUE THREAD

**Issue by dngray** [glutanimate/PDFMtEd#8]
Are there any plans to update this for Python 3?

Python 2 will be unmaintained past January 2020. There will be no Python 2.8 and it seems like distributions will drop support too.

https://www.python.org/dev/peps/pep-0373/
https://python3statement.org/#sections20-statement

**Comment by sonibla** [comment]
I just made a pull request to port PDFMtEd to Python 3

**Comment by glutanimate** [comment]
Fixed with #10 (thanks to @sonibla !)
